### ISSUE TITLE
ServiceException can't handle non-JSON response

### ISSUE THREAD

**Issue by ceberling-wescalehq** [meplato/mall-java-client#2]
Hi,

last week we have been getting a lot of these errors in our log:

``` java.lang.Exception: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.wescale.mall.app.job.CatalogDownloadJob.execute(CatalogDownloadJob.java:147) ~[classes/:?]
	at com.wescale.mall.app.scheduler.DistributedScheduler.execute(DistributedScheduler.java:103) ~[classes/:?]
	at com.wescale.mall.app.scheduler.DistributedScheduler.trigger(DistributedScheduler.java:190) [classes/:?]
	at com.wescale.mall.app.scheduler.DistributedScheduler.access$500(DistributedScheduler.java:25) [classes/:?]
	at com.wescale.mall.app.scheduler.DistributedScheduler$2.run(DistributedScheduler.java:246) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_112]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_112]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_112]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_112]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221) ~[gson-2.5.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:861) ~[gson-2.5.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:826) ~[gson-2.5.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:775) ~[gson-2.5.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:747) ~[gson-2.5.jar:?]
	at com.meplato.mall.ApacheHttpResponse.getBodyJSON(ApacheHttpResponse.java:124) ~[meplato-mall-1.0.5.jar:?]
	at com.meplato.mall.ServiceException.fromResponse(ServiceException.java:58) ~[meplato-mall-1.0.5.jar:?]
	at com.meplato.mall.ApacheHttpClient.execute(ApacheHttpClient.java:143) ~[meplato-mall-1.0.5.jar:?]
	at com.meplato.mall.products.Service$ScrollService.execute(Service.java:314) ~[meplato-mall-1.0.5.jar:?]
	at com.wescale.mall.app.job.CatalogDownloadJob.nextPage(CatalogDownloadJob.java:186) ~[classes/:?]
	at com.wescale.mall.app.job.CatalogDownloadJob.execute(CatalogDownloadJob.java:91) ~[classes/:?]
	... 11 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:388) ~[gson-2.5.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:210) ~[gson-2.5.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:861) ~[gson-2.5.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:826) ~[gson-2.5.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:775) ~[gson-2.5.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:747) ~[gson-2.5.jar:?]
	at com.meplato.mall.ApacheHttpResponse.getBodyJSON(ApacheHttpResponse.java:124) ~[meplato-mall-1.0.5.jar:?]
	at com.meplato.mall.ServiceException.fromResponse(ServiceException.java:58) ~[meplato-mall-1.0.5.jar:?]
	at com.meplato.mall.ApacheHttpClient.execute(ApacheHttpClient.java:143) ~[meplato-mall-1.0.5.jar:?]
	at com.meplato.mall.products.Service$ScrollService.execute(Service.java:314) ~[meplato-mall-1.0.5.jar:?]
	at com.wescale.mall.app.job.CatalogDownloadJob.nextPage(CatalogDownloadJob.java:186) ~[classes/:?]
	at com.wescale.mall.app.job.CatalogDownloadJob.execute(CatalogDownloadJob.java:91) ~[classes/:?]
	... 11 more
```

It seems like the service call failed, but the server did not return a JSON formatted message, so the Client was unable to deserialize it into a ServiceException. It would be nice to have some sort of fallback to be able to read the server response in such a case.

**Comment by olivere** [comment]
Yep. Sorry for that.

We had some issues this week in the cluster. LB had some issues with the backend and reported classy HTML files back. Maybe that was the issue.

I will talk to devops if they can report back a JSON error object when upstream is gone.
